### ISSUE TITLE
Research project descriptions

### ISSUE THREAD

**Issue by Madlark** [AobaKuma/Fortification-Citadel#12]
Hello again! I don't think https://github.com/AobaKuma/Fortification-Citadel/blob/main/Languages/English/DefInjected/ResearchProjectDef/FTC_ResearchProject.xml contains all research project descriptions. ENIAC, Lathe and others are missing. Am I looking in the wrong place?

**Comment by AobaKuma** [comment]
the Eniac and Lathe are included in the core mod, so i guess it's not an issue

**Comment by Madlark** [comment]
Thank you. I've updated the remaining files. If you don't mind, Id like to see the text in game and then come back for some additional polishing, if necessary.

 Would you like me to take a look at the core mod translation as well?

**Comment by AobaKuma** [comment]
that'll help a lot :3 , i'll update the core mod github this week
